![pays_oz](pays_oz.png)

\begin{align*}
P([X_1 = P]) &= P([X_1 = P] \cap [X_0 = P] \cup [X_1 = P] \cap [X_0 = S] \cup [X_1 = P] \cap [X_0 = N]) \\
             &= P([X_1 = P] \cap [X_0 = P]) + P([X_1 = P] \cap [X_0 = S]) + P([X_1 = P] \cap [X_0 = N]) \\
             &= P_{X_0 = P}(X_1 = P) \times P(X_0 = P) + P_{X_0 = S}(X_1 = P) \times P(X_0 = S) + P_{X_0 = N}(X_1 = P) \times P(X_0 = N) \\
             &= 0,6 \times P([X_0 = P]) + 0,1 \times P([X_0 = S]) + 0,3 \times P([X_0 = N]) \\ \\

P([X_1 = S]) &= 0,2 \times P([X_0 = P]) + 0,6 \times P([X_0 = S]) + 0,2 \times P([X_0 = N]) \\ \\

P([X_1 = N]) &= 0,4 \times P([X_0 = P]) + 0 \times P([X_0 = S]) + 0,6 \times P([X_0 = N]) \\
\end{align*}

$
A = 
\left(
\begin{array}{c|cccccccccccc}
 & P & S & N \\ \hline
P & 0.6 & 0.1 & 0.3 \\
S & 0.2 & 0.6 & 0.2 \\
N & 0.4 & 0.0 & 0.6
\end{array}
\right)
$

\begin{array}{cc}
 & µ_0 = \begin{pmatrix}
   P[X_0 = P] \\
   P[X_0 = S] \\
   P[X_0 = N]
  \end{pmatrix}
\\
  A = \begin{pmatrix}
   0,6 & 0,1 & 0,3 \\ 
   0,2 & 0 & 0,6 \\ 
   0,4 & 0.0 & 0.6
  \end{pmatrix}
 &
  \begin{pmatrix}
   ...
  \end{pmatrix} = µ_1
\end{array}


\begin{array}{cc}
 & µ_0 = \begin{pmatrix}
   P[X_0 = 1] \\
   P[X_0 = 0] \\
   P[X_0 = 0]
  \end{pmatrix}
\\
  A = \begin{pmatrix}
   0,6 & 0,1 & 0,3 \\ 
   0,2 & 0 & 0,6 \\ 
   0,4 & 0.0 & 0.6
  \end{pmatrix}
 &
  \begin{pmatrix}
   ...
  \end{pmatrix} = µ_1
\end{array}

In [16]:
import numpy as np

mu_0 = np.array([[1], [0], [0]])

A = np.array([
    [0.6, 0.1, 0.3],
    [0.2, 0.6, 0.2],
    [0.4, 0.0, 0.6]
])

A = A.T

def calculate_distribution(mu_0, A, steps=1):
    mu_t = mu_0
    for _ in range(steps):
        mu_t = A @ mu_t
    return mu_t

steps = 50

for t in range(steps):
    mu_t = calculate_distribution(mu_0, A, t)
    print(f"Distribution µ_{t}:\n{mu_t}\n")

Distribution µ_0:
[[1]
 [0]
 [0]]

Distribution µ_1:
[[0.6]
 [0.1]
 [0.3]]

Distribution µ_2:
[[0.5 ]
 [0.12]
 [0.38]]

Distribution µ_3:
[[0.476]
 [0.122]
 [0.402]]

Distribution µ_4:
[[0.4708]
 [0.1208]
 [0.4084]]

Distribution µ_5:
[[0.47   ]
 [0.11956]
 [0.41044]]

Distribution µ_6:
[[0.470088]
 [0.118736]
 [0.411176]]

Distribution µ_7:
[[0.4702704]
 [0.1182504]
 [0.4114792]]

Distribution µ_8:
[[0.470404  ]
 [0.11797728]
 [0.41161872]]

Distribution µ_9:
[[0.47048534]
 [0.11782677]
 [0.41168789]]

Distribution µ_10:
[[0.47053172]
 [0.1177446 ]
 [0.41172369]]

Distribution µ_11:
[[0.47055742]
 [0.11769993]
 [0.41174265]]

Distribution µ_12:
[[0.4705715]
 [0.1176757]
 [0.4117528]]

Distribution µ_13:
[[0.47057916]
 [0.11766257]
 [0.41175827]]

Distribution µ_14:
[[0.47058332]
 [0.11765546]
 [0.41176122]]

Distribution µ_15:
[[0.47058557]
 [0.11765161]
 [0.41176282]]

Distribution µ_16:
[[0.47058679]
 [0.11764952]
 [0.41176369]]

Distribution µ_17:
[[0.47058745]
 [0.11764839]
 [0.41

In [17]:
from sympy import Matrix

mu_0 = Matrix([[1], [0], [0]])

A = Matrix([
    [0.6, 0.1, 0.3],
    [0.2, 0.6, 0.2],
    [0.4, 0.0, 0.6]
])

A = A.T

def calculate_distribution_symbolic(mu_0, A, steps=1):
    mu_t = mu_0
    for _ in range(steps):
        mu_t = A * mu_t
    return mu_t

steps = 50

for t in range(steps):
    mu_t = calculate_distribution_symbolic(mu_0, A, t)
    print(f"Distribution µ_{t}:\n{mu_t}\n")

Distribution µ_0:
Matrix([[1], [0], [0]])

Distribution µ_1:
Matrix([[0.600000000000000], [0.100000000000000], [0.300000000000000]])

Distribution µ_2:
Matrix([[0.500000000000000], [0.120000000000000], [0.380000000000000]])

Distribution µ_3:
Matrix([[0.476000000000000], [0.122000000000000], [0.402000000000000]])

Distribution µ_4:
Matrix([[0.470800000000000], [0.120800000000000], [0.408400000000000]])

Distribution µ_5:
Matrix([[0.470000000000000], [0.119560000000000], [0.410440000000000]])

Distribution µ_6:
Matrix([[0.470088000000000], [0.118736000000000], [0.411176000000000]])

Distribution µ_7:
Matrix([[0.470270400000000], [0.118250400000000], [0.411479200000000]])

Distribution µ_8:
Matrix([[0.470404000000000], [0.117977280000000], [0.411618720000000]])

Distribution µ_9:
Matrix([[0.470485344000000], [0.117826768000000], [0.411687888000000]])

Distribution µ_10:
Matrix([[0.470531715200000], [0.117744595200000], [0.411723689600000]])

Distribution µ_11:
Matrix([[0.470557424000000]